import {
  LayoutDashboard,
  UserCheck,
  Building2,
  ShoppingBag,
  Truck,
  Package,
  TicketPercent,
  CreditCard,
  Clock3,
  RotateCcw,
  Percent,
  BarChart3,
  Users,
  ScrollText,
  ExternalLink,
  LogOut,
  Search,
  Bell,
  Moon,
  UserRound,
  Plus,
  Box,
  Factory,
  Warehouse,
  Network,
  Activity,
  Database,
  Boxes,
  Store,
  ClipboardList,
} from "lucide-react";
import type { LucideIcon } from "lucide-react";

export const adminNavIcons: Record<string, LucideIcon> = {
  "/admin": LayoutDashboard,
  "/admin/activity": Activity,
  "/admin/approvals": UserCheck,
  "/admin/customers": Building2,
  "/admin/distributors": Network,
  "/admin/wholesalers": Boxes,
  "/admin/retail": Store,
  "/admin/orders": ShoppingBag,
  "/admin/orders/new": Plus,
  "/admin/suppliers": Factory,
  "/admin/logistics": ShoppingBag,
  "/admin/logistics/shipments": Truck,
  "/admin/logistics/packing-lists": ClipboardList,
  "/admin/profile": UserRound,
  "/admin/catalog": Package,
  "/admin/coupons": TicketPercent,
  "/admin/credit": CreditCard,
  "/admin/aging": Clock3,
  "/admin/notifications": Bell,
  "/admin/rma": RotateCcw,
  "/admin/commissions": Percent,
  "/admin/reports": BarChart3,
  "/admin/staff": Users,
  "/admin/system": Database,
  "/admin/audit": ScrollText,
};

export {
  ExternalLink,
  LogOut,
  Search,
  Bell,
  Moon,
  UserRound,
  Plus,
  Package,
  Box,
  UserCheck,
  ShoppingBag,
  Building2,
  Warehouse,
  Factory,
};
